create database boschtrainingdb
go

use boschtrainingdb
go

create table Customers (
	CustomerId INT IDENTITY PRIMARY KEY,
	CustomerName VARCHAR(50),
	Address VARCHAR(50),
	CreditLimit INT,
	ActiveStatus BIT,
	Remarks TEXT
);
go

insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Raleigh Vellden', 'Novyy Karachay', 25439, 1, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Glad Absalom', 'Shuangmiao', 17536, 0, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Sheffield Lamperd', 'Wurigelebur', 15423, 1, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Candie Organ', 'Haihui', 31028, 1, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Lissy Hewlings', 'Panjerrejo', 38007, 1, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Hastie Orteau', 'San Antonio', 47319, 1, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Osborne Plom', 'Khodasy', 44075, 0, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Wallis Kaes', 'Gelin', 45336, 1, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Freddy Proudman', 'Honglai', 49870, 0, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Rosy Nellies', 'Nar''yan-Mar', 10563, 0, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Garfield Deverille', 'Batuidu', 14351, 0, 'Fusce consequat. Nulla nisl. Nunc nisl.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Juieta Winman', 'Rostokino', 40954, 1, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Der Kennifick', 'Prado Siongco', 45800, 1, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Cortie Chippindall', 'Vicuña', 14386, 1, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Darrell Frankema', 'Corinto', 31024, 1, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Brynne Caren', 'Onsala', 15008, 0, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Sharon Allwell', 'Piribebuy', 25753, 1, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Faith Krahl', 'Coruña, A', 42890, 1, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Ernesta Persich', 'Kassiri', 33890, 0, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Olag Parlet', 'Izra‘', 23765, 0, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Janeva Hayland', 'Aranitas', 38947, 0, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Larina Olfert', 'Saltsjö-Boo', 11201, 1, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Fiona Fortnum', 'Cergy-Pontoise', 38426, 1, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Verile Yurenev', 'Pasar', 32529, 1, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Wakefield Silly', 'Santa Bárbara', 31356, 1, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Niven Hundey', 'Leyuan', 43400, 1, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Ashleigh Salmons', 'Laveiras', 33214, 0, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Jose Dormer', 'Mała Wieś', 12216, 1, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Edgardo Escott', 'Värnamo', 36636, 1, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Moe Dik', 'Avesta', 10369, 0, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Jaquelin Syer', 'Sevan', 47446, 0, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Bogart Leggott', 'Khiwa', 42789, 0, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Caleb Mowson', 'Hongtang', 49034, 1, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Wendy Le Noury', 'Delta del Tigre', 25724, 0, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Tessa Coppens', 'Almalaguês', 42901, 1, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Dino Rekes', 'Dzyatlava', 41170, 0, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Bibby Caulfield', 'Huolianpo', 32233, 0, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Rois Fellgate', 'Jatiprahu', 18215, 1, 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Ricki Harrington', 'Mauraro', 16295, 0, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Rory Thouless', 'Tanabe', 16991, 0, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Linzy Cristofolini', 'Zaslawye', 33022, 1, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Neale Tyres', 'Poniatowa', 41166, 0, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Olia Dicey', 'Eleftheroúpolis', 17366, 1, 'Fusce consequat. Nulla nisl. Nunc nisl.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Marlo Aspinal', 'Novopodrezkovo', 19665, 0, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Olva Giraths', 'Rio Largo', 37895, 0, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Hal Knivett', 'Chilecito', 18929, 1, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Wilone Scholey', 'Muara', 18627, 1, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Connor Villaret', 'Shuanghe', 33792, 0, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Cobb Linkin', 'Zhongguan', 41478, 1, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Linn Ramelot', 'Kubangkondanglapangan', 38519, 0, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Nicholas Gibson', 'Quinta da Torre', 46116, 0, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Marietta Briggdale', 'Zvečan', 27766, 1, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Gunter McKitterick', 'Hamburg', 18996, 1, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Nester Ness', 'Krajan', 31308, 1, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Edythe Maes', 'Nogueira', 30862, 1, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Netti Tapsfield', 'Karangasem', 40536, 0, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Hunt Gravey', 'Jicun', 47388, 1, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Yorke Sebright', 'El Paso', 46706, 1, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Darla O''Curran', 'Zhuhong', 26756, 1, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Jaclyn Lucius', 'Palenggihan', 43239, 1, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Bibbie Casford', 'Jiaoshi', 45446, 1, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Raquel Ambrozewicz', 'Soutinho', 17004, 0, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Cliff Astlet', 'Khanabad', 17811, 1, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Jethro Element', 'Chatturat', 21980, 0, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Parke Sneden', 'Panacan', 28891, 1, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Porter Lowdes', 'Joševa', 13348, 0, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Maegan Hullin', 'Lücheng', 23088, 1, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Cassy Baldacchino', 'Hradec Králové', 12951, 0, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Chev Mahady', 'Martyush', 37047, 0, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Jordon Huison', 'Yovon', 28892, 1, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Heddi Fydo', 'Poja', 34616, 0, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Teri Brettell', 'Sumberan', 30080, 0, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Garrik Manueau', 'Dudchany', 20315, 1, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Fowler Krishtopaittis', 'Lamawan', 10326, 0, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Lenette Harrisson', 'Umeå', 38677, 0, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Duncan Charley', 'Staten Island', 32535, 1, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Mort Petracchi', 'Kinéta', 46132, 1, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Devinne Rosettini', 'Chinchero', 16950, 1, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Tonia Kenealy', 'Sandnes', 25964, 0, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Alexandr Jodrelle', 'Agboville', 18378, 0, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Herculie Boyson', 'Ketitang Wetan', 15221, 0, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Ingar Dmiterko', 'Baryshivka', 16150, 1, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Chaim Winstanley', 'Kamieniec Ząbkowicki', 32863, 0, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Sterne Collyear', 'Issad', 46065, 1, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Kaitlyn Kristof', 'Meia Via', 22803, 0, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Barbra Geerdts', 'Alilem', 20794, 0, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Ruth Rudall', 'København', 44020, 1, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Gerrie Clacson', 'Bucay', 43936, 0, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Ephraim Barrs', 'Puqian', 33565, 1, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Steffane Vale', 'Bordeaux', 35478, 0, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Laraine Shank', 'Ai Tu', 29720, 1, 'Fusce consequat. Nulla nisl. Nunc nisl.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Caterina Heymann', 'Vyshniy Volochëk', 49964, 0, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Gilly Kingsnorth', 'Langpas', 18595, 0, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Gannie Formoy', 'Des Moines', 28068, 1, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Berni Aleevy', 'São José do Rio Preto', 13820, 1, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Greer Burghill', 'Chengyang', 35445, 1, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Ainslee Gehring', 'Heyou', 30740, 0, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Chandra Halls', 'Tacheng', 10635, 1, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Cletis Lavall', 'Sidi Yahya Ou Saad', 19362, 1, 'In congue. Etiam justo. Etiam pretium iaculis justo.');
insert into Customers (CustomerName, Address, CreditLimit, ActiveStatus, Remarks) values ('Wilfred Grishenkov', 'Sida', 12469, 0, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.');
go